# -*- coding: utf-8 -*-
"""
Created on Mon Sep 18 18:49:59 2023

Last Updated on May 27, 2025

@author: Mitch Haslehurst, Emily Rose Korfanty
"""

from ifs import *

st.set_page_config(layout="wide")

st.title("IFS Python")

st.markdown("*Created by Mitch Haslehurst, PhD and Emily Korfanty*")

st.write("This app uses Python to generate fractal images from 2D affine iterated function systems (IFS).")


st.markdown("""
- Learn what a 2D affine IFS is - link to page
- Learn about the theory behind fractals generated by IFS - link to page
- Explore fractals generated by our built-in IFS - link to page
- Make your own fractals by building your own IFS - link to page
	""")
