# -*- coding: utf-8 -*-
"""
Created on Mon Sep 18 18:49:59 2023

Last Updated on May 27, 2025

@author: Mitch Haslehurst, Emily Rose Korfanty
"""

from ifs import *

st.set_page_config(layout="wide")

st.title("IFS Python")

st.write("This app uses Python to generate fractal images from 2D affine iterated function systems (IFS).")

st.write("The app allows you to explore the fascinating world of fractals generated by IFS. You can learn about the theory behind these fractals, see examples of classical IFS, and even create your own custom IFS to generate unique fractal images.")

if False:
	st.markdown("""
	- Learn what a 2D affine IFS is - link to page
	- Learn about the theory behind fractals generated by IFS - link to page
	- Explore fractals generated by our built-in IFS - link to page
	- Make your own fractals by building your own IFS - link to page
		""")

st.header("About the authors")

col1, col2 = st.columns(2, gap = "medium")

with col1:
	st.subheader("Mitch Haslehurst, PhD")
	st.image("mitch_headshot.jpg", width = 200)
	st.write("Mitch is a mathematician currently working as a data scientist for the Ontario provincial government. He has a passion for making complex concepts accessible and engaging through interactive visualizations. Mitch has experience in both academia and industry, where he has worked on projects involving data analysis, educational research, and educational content creation.")
	st.link_button("LinkedIn Profile", "https://www.linkedin.com/in/mitch-haslehurst/")

with col2:
	st.subheader("Emily Korfanty")
	st.image("emily_headshot.jpg", width = 200)
	st.write("Emily is a PhD candidate in mathematics at the University of Alberta and is currently working as an Economics and Investment Research Intern at AIMCo (Alberta Investment Management Corporation). Her academic research focuses on mathematical diffraction theory, while her industry work explores applications of time series analysis and convex optimization in finance. Emily is dedicated to making mathematics more approachable through thoughtfully designed visualizations.")
	st.link_button("LinkedIn Profile", "https://www.linkedin.com/in/emilykorfanty/")