import streamlit as st

st.header("Hutchinson's Theorem")

st.write("Hutchinson's Theorem in mathematics is what makes our app work! It is a fundamental result in the theory of iterated function systems (IFS) that guarantees the existence and uniqueness of an attractor for a given IFS. The theorem states that if an IFS consists of a finite set of contraction mappings on a complete metric space, then there exists a unique non-empty compact set that is invariant under the IFS. This set is called the attractor of the IFS.")

st.write("In simpler terms, Hutchinson's Theorem tells us that if we have a collection of functions that bring points closer together (contractions), then there will be a unique shape (the attractor) that remains unchanged when we apply all the functions in the IFS. This attractor is what we see as the fractal generated by the IFS.")

st.write("Hutchinson's Theorem is, in fact, a special case of the Contraction Mapping Theorem, which is a more general result in mathematical analysis. The Contraction Mapping Theorem states that if a function is a contraction on a complete metric space, then it has a unique fixed point. The set of all compact subsets of the metric space, equipped with the Hausdorff metric, forms a complete metric space. The IFS can be seen as a function that maps compact subsets to compact subsets, and if it is a contraction with respect to the Hausdorff metric, then it has a unique fixed point, which is the attractor of the IFS.")
         
st.write("The theorem is named after John E. Hutchinson, who proved it in 1981. It provides a rigorous mathematical foundation for the study of fractals generated by IFS and has been instrumental in the development of fractal geometry and its applications in various fields such as computer graphics, natural phenomena modeling, and more.")

st.write("In the context of our app, Hutchinson's Theorem ensures that when we select an IFS and iterate it starting from any initial shape, we will converge to the same attractor, which is the fractal image we are interested in exploring.")

st.write("To see Hutchinson's Theorem in action, you can go to the 'Classical IFS' page and select one of the built-in IFS options. As you iterate the functions, you'll see how the initial shape evolves and eventually converges to the unique attractor, demonstrating the theorem's guarantee of existence and uniqueness.")

st.write("If you're interested in the mathematical details of Hutchinson's Theorem, you can refer to the original paper by John E. Hutchinson titled 'Fractals and Self-Similarity' published in 1981, which provides a comprehensive explanation of the theorem and its implications in the study of fractals.")
